# Generated by Django 2.2.11 on 2020-03-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_activity', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('coordinates', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('activity', models.CharField(max_length=255)),
                ('id_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('id_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Building')),
            ],
        ),
    ]
