# Generated by Django 2.2.7 on 2020-03-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alias',
            new_name='Synonym',
        ),
    ]
