# Generated by Django 2.2.7 on 2020-04-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0002_auto_20200410_1332'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='Building',
        ),
        migrations.AlterModelTable(
            name='campus',
            table='Campus',
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
    ]
